services:
  - type: web       # The type being a web API
    name: nexus-backend   # The name you want to see on Render dashboard
    runtime: python       # Tell Render youâ€™re using Python
    buildCommand: pip install -r requirements.txt   # Install dependencies
    startCommand: gunicorn app:app                  # Start your server
    envVars:
      - key: PYTHON_VERSION
        value: 3.10